[tool.poetry]
name = "lunary"
version = "0.1.43"
description = "Observability, analytics and evaluations for AI agents and chatbots."
authors = ["lunary <hello@lunary.ai>"]
readme = "README.md"
repository = "https://github.com/lunary/lunary.ai/"
documentation = "https://lunary.ai/docs/py/usage"
keywords = ["Lunary", "lunary.ai", "Langchain", "AI", "Analytics", "Monitoring"]

[tool.poetry.dependencies]
python = "^3.10"
setuptools = "^69.1.1"
requests = "^2.31.0"
tenacity = "^8.2.3"
opentelemetry-api = "^1.21.0"
opentelemetry-sdk = "^1.21.0"
packaging = "^23.2"
chevron = "^0.14.0"
openai = { version = "^1.13.0", optional = true }
langchain = { version = "^0.1.10", optional = true }

[tool.poetry.extras]
openai = ["openai"]
langchain = ["langchain"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
